---
applications:
  - name: dsnap-registration
    path: ../build
    buildpack: nginx_buildpack
    routes:
      - route: dsnap-registration-dev.app.cloud.gov
    env:
      RULES_SERVICE_URL: https://dsnap-rules-staging.app.cloud.gov
      REGISTRATION_SERVICE_URL: https://dsnap-registration-service-staging.app.cloud.gov
