export default {
  "basicInfo":{
     "personId": 0,
     "phone":"2165555555",
     "email":"adam@email.biz",
     "residenceAddress":{
        "street1":"250 Oakland Way",
        "street2":"",
        "city":"Oakland",
        "state":"CA",
        "zipcode":"94612"
     },
     "mailingAddress":{
        "street1":"365 Campus Rd",
        "street2":"",
        "city":"Cleveland",
        "state":"OH",
        "zipcode":"44121"
     },
     "county":"Alameda",
     "currentMailingAddress":"false"
  },
  "identity":{
     "personalInfo":{
        "stateId":"Y9456A7"
     }
  },
  "household":{
     "numMembers":1,
     "currentMemberIndex":0,
     "members":[
        {
           "name":{
              "firstName":"Adam",
              "middleName":"",
              "lastName":"B"
           },
           "dob":{
              "month":"01",
              "day":"01",
              "year":"1989"
           },
           "sex":"male",
           "ssn":"111111111",
           "race":"",
           "hasFoodAssistance":false,
           "hasOtherJobs":"no",
           "hasJobs":true,
           "assetsAndIncome":{
              "hasIncome":true,
              "incomeSources":{
                 "selfEmployed":{
                    "applicable":false,
                    "value":null
                 },
                 "unemployment":{
                    "applicable":true,
                    "value":200
                 },
                 "cashAssistance":{
                    "applicable":false,
                    "value":null
                 },
                 "disability":{
                    "applicable":false,
                    "value":null
                 },
                 "socialSecurity":{
                    "applicable":false,
                    "value":null
                 },
                 "veteransBenefits":{
                    "applicable":false,
                    "value":null
                 },
                 "alimony":{
                    "applicable":false,
                    "value":null
                 },
                 "childSupport":{
                    "applicable":false,
                    "value":null
                 },
                 "otherSources":{
                    "applicable":false,
                    "value":null
                 }
              },
              "jobs":[
                 {
                    "employerName":"TTS",
                    "pay":"1000",
                    "isStateAgency":"no"
                 },
                 {
                    "employerName":"Apollo",
                    "pay": "500",
                    "isStateAgency":"no"
                 },
              ],
              "moneyOnHand":"1000"
           }
        },
        {
          "name":{
             "firstName":"Bob",
             "middleName":"",
             "lastName":"Ross"
          },
          "dob":{
             "month":"01",
             "day":"01",
             "year":"1949"
          },
          "sex":"male",
          "ssn":"111111112",
          "race":"",
          "hasFoodAssistance":false,
          "hasOtherJobs":"no",
          "hasJobs":true,
          "assetsAndIncome":{
             "hasIncome":true,
             "incomeSources":{
                "selfEmployed":{
                   "applicable":true,
                   "value":10000
                },
                "unemployment":{
                   "applicable":false,
                   "value":null
                },
                "cashAssistance":{
                   "applicable":false,
                   "value":null
                },
                "disability":{
                   "applicable":false,
                   "value":null
                },
                "socialSecurity":{
                   "applicable":false,
                   "value":null
                },
                "veteransBenefits":{
                   "applicable":false,
                   "value":null
                },
                "alimony":{
                   "applicable":false,
                   "value":null
                },
                "childSupport":{
                   "applicable":false,
                   "value":null
                },
                "otherSources":{
                   "applicable":false,
                   "value":null
                }
             },
             "jobs":[
               //  {
               //     "employerName":"USPS",
               //     "pay":"10000",
               //     "isStateAgency":"no"
               //  },
             ],
             "moneyOnHand":"5"
          }
       }
     ]
  },
  "impact":{
     "lostOrInaccessibleIncome":"yes",
     "inaccessibleMoney":"no",
     "buyFood":"yes",
     "noOtherExpenses":false,
     "otherExpenses":{
        "foodLoss":{
           "applicable":true,
           "value":129
        },
        "evacuation":{
           "applicable":false,
           "value":null
        },
        "tempShelter":{
           "applicable":true,
           "value": 550
        },
        "repairs":{
           "applicable":false,
           "value":null
        },
        "other": {
           applicable: true,
           value: 1000
        }
     }
  },
  "resources":{
     "membersWithIncome": []
  },
  "currentSection":"basic-info",
  "currentStep":"applicant-name",
  "previousStep":"",
  "previousSection":"",
  "totalSteps":6,
  "step":1,
  "newJob":{
     "employerName":"",
     "pay":"",
     "isStateAgency":null
  },
  config: {
     useLocalStorage: true,
     language: 'en',
     disaster: ''
  }
};
